### ISSUE TITLE
Module kmod-sdhci is not enabled by and leads to lack of sdcard of high capacity support

### ISSUE THREAD

**Issue by sergey-brutsky** [Seeed-Studio/seeed-linux-openwrt#20]
Hello,

I'm trying to use sdcard for 256Gb in my [carrier board](https://www.seeedstudio.com/Dual-GbE-Carrier-Board-with-4GB-RAM-32GB-eMMC-RPi-CM4-Case-p-5029.html).

Unfortunately, this card is not working when plugged in. 
From what i found on the [openwrt forum](https://forum.openwrt.org/t/rbm33g-memory-expansion-microsd-solved/31649) the problem is that module [kmod-sdhci ](https://github.com/Seeed-Studio/seeed-linux-openwrt/blob/magic/configs/rpi_cm4_defconfig#L2510) is not enabled by default in the rpi4 config file

Could you please enable this module in the config and rebuild firmware for openwrt-bcm27xx-bcm2711-rpi-4-ext4-factory.img.gz ?

Thanks,
Sergey

**Comment by lakshanthad** [comment]
Hi @sergey-brutsky ,

It's done.

https://github.com/Seeed-Studio/seeed-linux-openwrt/commit/dab93cff7c9d1e16a62e7d100bfe9befa805d09b

**Comment by lakshanthad** [comment]
The GitHub action is set to compile the images every working day from Monday to Friday. So you will see the rebuilt firmware with the changes tomorrow. @sergey-brutsky

**Comment by sergey-brutsky** [comment]
Great ! Thank you !
