### ISSUE TITLE
Stable build of openwrt wanted

### ISSUE THREAD

**Issue by sergey-brutsky** [Seeed-Studio/seeed-linux-openwrt#22]
Hello,

I've noticed that your are building snapshot versions of openwrt firmware. 
Downloaded recent version from [here](https://onedrive.live.com/?authkey=%21AEcwsyZAovIBK%2DI&id=5219529519B9B6A1%2159783&cid=5219529519B9B6A1) and found out that openwrt version is
```
  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 21.02-SNAPSHOT, r16420+14-4b52d89531
 -----------------------------------------------------
```
This is a bit annoying because it is impossible to install some useful packages from openwrt repo.
For example:
```
opkg install ebtables
Installing ebtables (2018-06-27-48cff25d-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02-SNAPSHOT/packages/aarch64_cortex-a72/base/ebtables_2018-06-27-48cff25d-1_aarch64_cortex-a72.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.163-1-deb453573a04e7a02726b2659a2a3363) for kmod-ebtables
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ebtables found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for ebtables:
 * 	kernel (= 5.4.163-1-deb453573a04e7a02726b2659a2a3363)
 * opkg_install_cmd: Cannot install package ebtables.
```

From my understanding opkg is trying to download ebtables package from the [snapshot repo](https://downloads.openwrt.org/releases/21.02-SNAPSHOT/packages/aarch64_cortex-a72/base/ebtables_2018-06-27-48cff25d-1_aarch64_cortex-a72.ipk) that is far away from the snapshot has been used during the custom [firmware build](https://onedrive.live.com/?authkey=%21AEcwsyZAovIBK%2DI&id=5219529519B9B6A1%2159783&cid=5219529519B9B6A1)

Snapshot version ebtables depends on  kernel [`5.4.163-1-deb453573a04e7a02726b2659a2a3363`](https://downloads.openwrt.org/releases/21.02-SNAPSHOT/targets/bcm27xx/bcm2711/kmods/) but seeed firmware build contains kernel version `5.4.163-1-e22d32ef3487fd1594d4fa668b9eea2f`

I suspect that this problem could be with other packages depending on a specific kernel.

My question is could you please build "stable" openwrt version compatible with the standard stable packages repo.
For example current [stable version of openwrt  21.02.1](https://downloads.openwrt.org/releases/21.02.1/targets/bcm27xx/bcm2711/) with kernel 5.4.154 ?

OR 

Enable [ebtables functionality](https://github.com/Seeed-Studio/seeed-linux-openwrt/blob/magic/configs/rpi_cm4_defconfig#L2214-L2217) in your custom firmare build ?

**Comment by sergey-brutsky** [comment]
After reading a bit about custom openwrt builds it looks like that it is possible to compile any missing package in your custom builds.

There is a [openwrt image builder](https://openwrt.org/docs/guide-user/additional-software/imagebuilder).
This tools helps to easily compile/add any missing package from the custom openwrt build (like you are using).

To add image builder into your custom builds just [turn on this option in the config](https://github.com/Seeed-Studio/seeed-linux-openwrt/blob/magic/configs/rpi_cm4_defconfig#L389).
After that in the target folder after compilation file like openwrt-imagebuilder-XXX-bcm27xx-bcm2711.Linux-x86_64.tar.xz should appear.

By using this image builder it is possible to build/compile any missing package (like ebtables) without any difficulties.

Could you please turn set this option ?
Thanks

**Comment by Pillar1989** [comment]
@lakshanthad  any ideas ?

**Comment by lakshanthad** [comment]
@sergey-brutsky I have enabled Image Builder.

https://github.com/Seeed-Studio/seeed-linux-openwrt/commit/7135117d3a6b6ba38fd27f22968e6bb77e887afa

Please check.

**Comment by sergey-brutsky** [comment]
Hi @lakshanthad,

Sure, just waiting for the up to date version of custom firmware with image builder inside.
Are your building new versions daily ? 
Still do not see image builder in the recent builds [here](https://onedrive.live.com/?authkey=%21AEcwsyZAovIBK%2DI&id=5219529519B9B6A1%21963&cid=5219529519B9B6A1)

**Comment by lakshanthad** [comment]
Hi @sergey-brutsky,

You can check here.

https://github.com/Seeed-Studio/seeed-linux-openwrt/blob/magic/.github/workflows/build-cm4-openwrt.yml#L8

We are building during weekdays at 9a.m.

**Comment by sergey-brutsky** [comment]
Got it, as soon as I get it I will check if custom packages/kmods are working and let you know

Thanks !

**Comment by lakshanthad** [comment]
@sergey-brutsky 
Also, If you are interested in building on your local machine, you could try this:

1. sudo apt install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev  -y
2. mkdir openwrt-compile
3. cd openwrt-compile
2. git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b openwrt-21.02 openwrt
3. git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b magic config
4. cd openwrt
5. ./scripts/feeds update -a
6. ./scripts/feeds install-a
7. ln -s ../config/files/rpi/ files
8. cp ../config/configs/rpi_cm4_defconfig .config
9. make menuconfig
10. make -j<x> # example: make -j8

**Comment by sergey-brutsky** [comment]
Hey @lakshanthad, 

I will try your instructions after the weekends and let you know if it's successful.

**Comment by sergey-brutsky** [comment]
> * sudo apt install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev  -y
> * mkdir openwrt-compile
> * cd openwrt-compile
> * git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b openwrt-21.02 openwrt
> * git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b magic config
> * cd openwrt
> * ./scripts/feeds update -a
> * ./scripts/feeds install -a
> * ln -s ../config/files/rpi/ files
> * cp ../config/configs/rpi_cm4_defconfig .config
> * make menuconfig
> * make -j[x] # example: make -j8, x corresponds to number of CPU threads

I've tried these instructions and was able to reproduce your custom firmware builds with a specific kernel version (e22d32ef3487fd1594d4fa668b9eea2f).
But unfortunately when you need some package that depends on kmod-* kernel module (like kmod-ebtables) it forces build system to change kernel magic version that leads to producing new kernel version (incompatible with the original one).

So if we want to be able to use "official" openwrt builds for seeed rpi4 board we have to stick to the [original config](https://downloads.openwrt.org/releases/21.02.1/targets/bcm27xx/bcm2711/config.buildinfo).
In other cases we have to rebuild the whole firmware from scratch with required kernel modules :(

I think that it makes sense to experiment with the [official openwrt release](https://downloads.openwrt.org/releases/21.02.1/targets/bcm27xx/bcm2711/) for rpi4 board and discover what packages we need for normal lan/wifi/bluetooth/usb work

**Comment by anon-submittere** [comment]
I also think that it would be better if the seeed version of openwrt were based on the (latest) stable official release of openwrt.
I really don't need bleeding edge but rather a stable solution that needs the least amount of maintenance:
https://openwrt.org/faq/difference_between_a_release_and_a_trunk_build
Not to mention that this would also make installing packages a pain free experience.

An alternative that would also work would be to provide a script that can be run on the official openwrt release to:
1. install the necessary driver for the second ethernet
2. configure the second ethernet as dhcp server

**Comment by stepelu** [comment]
I also think that it would be better if the seeed version of openwrt were based on the (latest) stable official release of openwrt.
I really don't need bleeding edge but rather a stable solution that needs the least amount of maintenance:
https://openwrt.org/faq/difference_between_a_release_and_a_trunk_build
Not to mention that this would also make installing packages a pain free experience.

An alternative that would also work would be to provide a script that can be run on the official openwrt release to:

install the necessary driver for the second ethernet
configure the second ethernet as dhcp server

**Comment by sergey-brutsky** [comment]
Hey @stepelu, 
I've tried official stable opewrt release and was able to install it to seeed carrier board.
I've managed to get the second ethernet port/wifi/bluetooth working.
All this stuff was a bit tricky but ultimately it's working.
I'm documenting required steps in a separate repo for anyone interested in this work

**Comment by stepelu** [comment]
@sergey-brutsky that sounds great, please keep me in the loop I'm looking forward to testing it.

**Comment by sergey-brutsky** [comment]
@stepelu please check instructions [here](https://github.com/sergey-brutsky/openwrt-seeed-carrier-board)

**Comment by stepelu** [comment]
@sergey-brutsky thanks!
I've ordered the 2-pins jumper (required for setting the seeed board to flashing mode), I'll test on the 28th when it arrives

**Comment by sergey-brutsky** [comment]
Sure, let me know if it's working for you.
Maybe it makes sense to add this tutorial to the seeed wiki as an alternative solution.
@lakshanthad what do you think ?

**Comment by lakshanthad** [comment]
@sergey-brutsky Thank you for the efforts. I will first try your tutorial and test it.

**Comment by sergey-brutsky** [comment]
We also could support the work done in this PR https://github.com/openwrt/openwrt/pull/4893

**Comment by stepelu** [comment]
@sergey-brutsky I tested your instructions, a few comments:

## Re the ethernet adapter 
All good!

## Re the wifi module

First of all, package `kmod-brcmfmac` was already installed.
Also, it wasn't possible to install `brcmfmac-firmware-43455-sdio`:
<img width="612" alt="Screen Shot 2021-12-29 at 12 12 09" src="https://user-images.githubusercontent.com/6617696/147658479-def97a04-b2a0-46c2-b47f-360662193f47.png">
However, skipping the package installation produced a working setup (I think), in the sense that `dmesg` and `ip l show wlan0` produced the desired outputs.

## Re extending the space

This didn't work out.
I followed the instructions aside from the `+4G` option: I went with the default choice that uses the whole free space (btw: what was the advantage of only making 4GB available?)
All seemed fine.
However, at the very last step, following the reboot I get:
```
root@OpenWrt:~# resize2fs /dev/mmcblk0p2
resize2fs 1.45.6 (20-Mar-2020)
Filesystem at /dev/mmcblk0p2 is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 2
resize2fs: Invalid argument While checking for on-line resizing support
```
and indeed
```
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root               126.4M     19.0M    105.3M  15% /
tmpfs                     1.9G     56.0K      1.9G   0% /tmp
/dev/mmcblk0p1           63.9M     15.7M     48.2M  25% /boot
tmpfs                   512.0K         0    512.0K   0% /dev
```
Partitions now look like:
```
root@OpenWrt:~# fdisk /dev/mmcblk0

Welcome to fdisk (util-linux 2.36.1).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): p
Disk /dev/mmcblk0: 29.12 GiB, 31268536320 bytes, 61071360 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5452574f

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1 *      8192   139263   131072   64M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      147456 61071359 60923904 29.1G 83 Linux
```
Any idea what the issue could be?

**Comment by sergey-brutsky** [comment]
Hey @stepelu,

* I will fix instructions for wifi module in order to make setup more clear

* Regarding extending space.
Of course you can use all available space from your eMMC storage for `/dev/root` system but imho it makes no sense. `/dev/root` used mostly for "system" files/packages/modules and 30G it too much space for such needs. From my perspective it makes sense to give `/dev/root` partition 2-4Gb (should be enough for all possible use cases) and use other space for something useful, let's say non-system files/documents/configs etc. So it's worth considering creating /dev/mmcblk0p3 partition for the rest of space.

* Regarding this error `resize2fs: Invalid argument While checking for on-line resizing support`
It looks like that the filesystem on that partition is corrupted. To fix it I would do something like:

1) Stop all services using this partition.
2) `mount / -o remount,ro` <-- remount root partition to readonly mode
3) `fsck.ext4 -pn /dev/mmcblk0p2` <-- check & fix all errors on unclean filesystem
4) Reboot.
5) `resize2fs /dev/mmcblk0p2`

**Comment by BKPepe** [comment]
> We also could support the work done in this PR [openwrt/openwrt#4893](https://github.com/openwrt/openwrt/pull/4893)

No need. I thought that I would take a look earlier, but there were many things to solve. Because of it, I postponed it to the Christmas holidays and to the end of the year. I was in touch with Seeed studio. ;)

**Comment by stepelu** [comment]
> Regarding this error resize2fs: Invalid argument While checking for on-line resizing support
> It looks like that the filesystem on that partition is corrupted. To fix it I would do something like:
> ...

I tried but I get:
```
root@boss:~# mount / -o remount,ro
root@boss:~# fsck.ext4 -pn /dev/mmcblk0p2
e2fsck: Only one of the options -p/-a, -n or -y may be specified.
root@boss:~# fsck.ext4 -p /dev/mmcblk0p2
rootfs: clean, 1419/6656 files, 9947/32768 blocks
root@boss:~# fsck.ext4 -n /dev/mmcblk0p2
e2fsck 1.45.6 (20-Mar-2020)
rootfs: clean, 1419/6656 files, 9947/32768 blocks
```
After reboot I get:
```
root@boss:~# resize2fs /dev/mmcblk0p2
resize2fs 1.45.6 (20-Mar-2020)
Filesystem at /dev/mmcblk0p2 is mounted on /; on-line resizing required
old_desc_blocks = 1, new_desc_blocks = 2
Performing an on-line resize of /dev/mmcblk0p2 to 7615488 (4k) blocks.
resize2fs: Invalid argument While trying to add group #1
```
Which is a different error from before, I am puzzled.

**Comment by sergey-brutsky** [comment]
Hey @stepelu,

Could you please [follow these instructions](https://openwrt.org/docs/guide-user/installation/installation_methods/sd_card#expanding_the_filesystem) and let us know if it helps ?

**Comment by sergey-brutsky** [comment]
@BKPepe do you know if there is a more user-friendly way to increase `/dev/root` partition to some bigger value ?
Maybe it is possible to override some defaults via target config profile like in [this PR](https://github.com/openwrt/openwrt/pull/4191/files).
It looks like that all this work with fdisk/e2fsck/resize2fs is quite tricky and dangerous.

**Comment by stepelu** [comment]
> Could you please follow these instructions and let us know if it helps ?

That worked, had to answer yes to a number of questions (re fixing things). Thanks

**Comment by sergey-brutsky** [comment]
@stepelu thanks for your feedback. Manual updated taking into accounts your comments.

**Comment by mmhorda** [comment]
Stable build would be indeed wanted.
Could you please include kmod-rtl8812au  in your future builds.
It is impossible to install it via opkg because of the kernel version difference.
Thank you in advance

**Comment by BKPepe** [comment]
You most likely should wait until OpenWrt 22.03 is released as there are a few improvements for Seeed's router. There is already rc5 version.

**Comment by mmhorda** [comment]
> You most likely should wait until OpenWrt 22.03 is released as there are a few improvements for Seeed's router. There is already rc5 version.

That's interesting to know. Do you know if everything is going to work (hardware wise) out of the box I install openwrt 22.03 rc-5 by myself or I have t install some additional kernel modules?
Thank you in advance.

**Comment by stynoo** [comment]
> Do you know if everything is going to work (hardware wise) out of the box I install openwrt 22.03 rc-5 by myself or I have t install some additional kernel modules? Thank you in advance.
It all works out of the box...

**Comment by LynnL4** [comment]
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38
