### ISSUE TITLE
r8169-firmware and drivers update 

### ISSUE THREAD

**Issue by carlosrnardi** [Seeed-Studio/seeed-linux-openwrt#26]
Is it possible to enable this driver for the ethernet Realtek ethernet interface 8169?

**Comment by BKPepe** [comment]
It should be enough to do:
```
opkg update && opkg install kmod-r8169
```

Once you do it, it will also download ``kmod-phy-realtek`` and ``r8169-firmware``.

**Comment by orhiee** [comment]
from clean install for RPI, latest 2022.01.04 image in onedrive.

**Issue 1**
opkg update gives the below error:
Collected errors:
 opkg_download: Failed to download https://downloads.openwrt.org/releases/21.02-SNAPSHOT/packages/aarch64_cortex-a72/node/Packages.gz, wget returned 8.
opkg_download: Failed to download https://downloads.openwrt.org/releases/21.02-SNAPSHOT/packages/aarch64_cortex-a72/seeed/Packages.gz, wget returned 8.
**solution**
running `opkg install base-files` fixes the above error, not really an issue. 

**Issue 2**
Without applying any updates: trying "opkg install kmod-r8169" gives the error: (same also after updating base-files)
Collected errors:
 pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.168-1-0788d83a1525da40e4d0f7b1f5d6ee0e) for kmod-phy-realtek
 pkg_hash_fetch_best_installation_candidate: Packages for kmod-phy-realtek found, but incompatible with the architectures configured
pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.168-1-0788d83a1525da40e4d0f7b1f5d6ee0e) for kmod-r8169
pkg_hash_fetch_best_installation_candidate: Packages for kmod-r8169 found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package kmod-r8169.

**my lspci:** (after installing pciutils)
00:00.0 PCI bridge: Broadcom Inc. and subsidiaries BCM2711 PCIe Bridge (rev 20)
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

I have a RTL8111 card connected over pci, any help would be appreciated :)

**Comment by orhiee** [comment]
so looked trough the drive for kernel versions, 

12.28 5.4.163 - is the latest non ..168
12.31 5.4.168 - first image with ..168


same results as above

**Comment by carlosrnardi** [comment]
> It should be enough to do:
> 
> ```
> opkg update && opkg install kmod-r8169
> ```
> 
> Once you do it, it will also download `kmod-phy-realtek` and `r8169-firmware`.

Hi @BKPepe, I tried to install following this method, however, it return an error, the kernel was incompatible, I tried several different versions available on one drive(different kernel version), all same error, however, I follow Your recommendation from other question where You explained step by step how to download and compile the image, I did and added the kernel driver and it's working like a charm. If You have a chance to add this, would be great to not have the need to recompile the image again and again to have access to the new version.
Thanks

**Comment by danluckner** [comment]
> > It should be enough to do:
> > ```
> > opkg update && opkg install kmod-r8169
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once you do it, it will also download `kmod-phy-realtek` and `r8169-firmware`.
> 
> Hi @BKPepe, I tried to install following this method, however, it return an error, the kernel was incompatible, I tried several different versions available on one drive(different kernel version), all same error, however, I follow Your recommendation from other question where You explained step by step how to download and compile the image, I did and added the kernel driver and it's working like a charm. If You have a chance to add this, would be great to not have the need to recompile the image again and again to have access to the new version. Thanks

Hi @carlosrnardi. I'm trying to do the same thing but getting some errors. Could you share the step-by-step you used?

**Comment by carlosrnardi** [comment]
Hi @danluckner, I followed the procedure below as described by @lakshanthad in another request, I created a virtual machine in my computer windows machine using Hyper-V and install Debian on it, then I added the r8169-firmware driver to the .config file and compiled it. 
   Hope that helps!

    1. sudo apt install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev -y
    2. mkdir openwrt-compile
    3. cd openwrt-compile
    4. git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b openwrt-21.02 openwrt
    5. git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b magic config
    6. cd openwrt
    7. ./scripts/feeds update -a
    8. ./scripts/feeds install -a
    9. ln -s ../config/files/rpi/ files
    10. cp ../config/configs/rpi_cm4_defconfig .config
    11. make menuconfig
    12. make -j[x] # example: make -j8, x corresponds to number of CPU threads

**Comment by lakshanthad** [comment]
Hello everyone,

Can I close this issue now?
