### ISSUE TITLE
Some GitHub Actions jobs exceeds more than 360 minutes

### ISSUE THREAD

**Issue by BKPepe** [Seeed-Studio/seeed-linux-openwrt#27]
Reference:
- https://github.com/Seeed-Studio/seeed-linux-openwrt/actions/runs/1931485101
- https://github.com/Seeed-Studio/seeed-linux-openwrt/actions/runs/1932846146

Maybe this could help:
- https://github.community/t/script-timeout-exceed-360-minutes/149641

**Comment by lakshanthad** [comment]
Hello @BKPepe,

I tried this with a forked repo and still got the same 6 hours timeout problem. It seems that there is a job execution time limitation, even though you extend it by using "timeout-minutes" inside the YAML file. You can refer here:
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

The issue has been discussed here as well:
https://stackoverflow.com/questions/68187987/github-actions-job-timeout

It seems that a solution can be to have a self-hosted runner or try to split the build into two.

Do you have any other ideas for a solution?

**Comment by LynnL4** [comment]
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38
