### ISSUE TITLE
Can't boot to completed. Reflashed OpenWrt image file on Dual Gigabit Ethernet Carrier Board for Raspberry Pi CM4 with the firmware from 2022-03-02 to 2022-05-05 .

### ISSUE THREAD

**Issue by Mchatpoj** [Seeed-Studio/seeed-linux-openwrt#29]
I reflashed OpenWrt image file on Dual Gigabit Ethernet Carrier Board for Raspberry Pi CM4 with the firmware from 2022-03-02 to 2022-05-05 that was linked from the Seeed Wiki page; from here:
https://onedrive.live.com/?authkey=!AEcwsyZAovIBK-I&id=5219529519B9B6A1!93186&cid=5219529519B9B6A1
I see this as the final output on the display and and white light onboard is flashing . it can't boot to complete. Please ' Tell me how to correct OpenWrt on Dual Gigabit Ethernet Carrier Board for Raspberry Pi CM4 emmc boot this issue
![Uploading 18F3B84E-09FC-4B0E-A2DD-3C091897B559.jpg…]![874EC8E1-574B-46D6-87D3-AA4D8E92EEBD](https://user-images.githubusercontent.com/26154168/167238160-ed295196-e033-4ff8-b524-067c4b403d54.jpg)
![18F3B84E-09FC-4B0E-A2DD-3C091897B559](https://user-images.githubusercontent.com/26154168/167238177-d400938f-7179-48f1-8397-7142f3b6924d.jpg)
.

**Comment by LynnL4** [comment]
Thank you for your feedback, as the CI of this project automatically merges the upstream code and compiles the firmware, we did not test every firmware. We are now tracking these changes and trying to fix them. To avoid errors, we will remove the unworking firmware and turn off CI until the problem is solved, then turn it back on. Thanks!

**Comment by kurzninja** [comment]
I am also having this same issue as well. I had to install the 2022-02-28 version to get it working and even it has issues as well. I would report the problem but it doesn't seem worth reporting on such an old version. Any suggestions?

**Comment by LynnL4** [comment]
Yes, we noticed that in March https://github.com/Seeed-Studio/seeed-linux-openwrt/commit/2d69d098e0c339ab594ccd54f74784d94e2c4a9a , openwrt updated its kernel version, which sent a conflict with some configurations of this project, which we are really fixing.  You can first describe the problem you bumped down, and we can verify it after the fix
