### ISSUE TITLE
Builds don't work on a CM4 8GB

### ISSUE THREAD

**Issue by Dutchy-** [Seeed-Studio/seeed-linux-openwrt#31]
Whenever I try to run Seeed OpenWRT on my new CM4 8GB (CM4108032) using the Dual Gigabit Carrier Board the system won't boot

I get the following error on screen:

```
start4.elf: is not compatible
This board requires newer software
```

I've traced this to a problem in OpenWRT stable: that also will not run, with the same error.
However, the latest release candidate for OpenWRT works fine!

I've tried building Seeed OpenWRT with the upstream rc by replacing 21.02 in the scripts with 22.03 to get the release candidate, but sadly that results in conflicts.

Is there a way to get the stable working on my compute module, or can you create a build based on the openwrt release candidate?

**Comment by muscovitebob** [comment]
I'm having the same issue with the boot error on this board with a CM4 4GB (CM4104032) with the latest build off of OneDrive. A Raspberry Pi OS boots just fine. Would appreciate a release to support this hardware.

**Comment by mschirrmeister** [comment]
I see the same error with the latest firmware from `2022-07-18`.
I have tried **22.03.0-rc6** from https://downloads.openwrt.org/releases/22.03.0-rc6/targets/bcm27xx/bcm2711/ and that one boots fine.

Will there be an official OpenWRT firmware release from Seeed Studio?

**Comment by LynnL4** [comment]
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38
