### ISSUE TITLE
sysupgrade?

### ISSUE THREAD

**Issue by K2IE** [Seeed-Studio/seeed-linux-openwrt#32]
I'm attempting a sysupgrade to get to a build based on Openwrt 22.03.0 rc5 on top of my own build based on the seeed provided .config.

Is this known to work?  So far, using the bcm27xx/bcm2711 (which now has 78xx lan driver support) ext4 sysupgrade image, I can apply it, the system reboots, and comes back up onder the original version as if the sysupgrade was never applied.  I wonder if this has something to do with the eMMC on the CM4?

Thoughts, comments, guidance?

**Comment by mmhorda** [comment]
It seems like it has something to do with not enough free space in /tmp
sysupgrade requires files to be copied there before actual sysupgrade and it has only 2Gb in size when latest images have 2.5Gb when unpacked.

**Comment by K2IE** [comment]
I remounted /tmp with 3G and tried the upgrade.  It had no effect.

`mount -t tmpfs -o remount,size=3G tmpfs /tmp`

**Comment by LynnL4** [comment]
Close it, then discuss it here https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/38
