### ISSUE TITLE
Is it just me? SLOW Throughput

### ISSUE THREAD

**Issue by charliebearsson** [Seeed-Studio/seeed-linux-openwrt#34]
Hi!
Is it just me that are experincing slow throughput after a while? Sometimes as low as 30mbit on a 500 mbit line. A reboot of the router solves the problem. But it reacures every 2 days. Is there a way to install the RPI4 version of openwrt instead of SEEED studios own version? And if, do I need to install any the drivers for the second NIC? 

Not the newest version of openWRT from SEEED, haven't been updated since august or september.

**Comment by kurzninja** [comment]
This happens to me. I have a 150 mb connection and it will gradually slow over time down into the 20s or even single digits. A reboot fixes it for a while. I try to keep my version of the SEEED firmware up to date also so it's not just older versions with the issue.

**Comment by charliebearsson** [comment]
> This happens to me. I have a 150 mb connection and it will gradually slow over time down into the 20s or even single digits. A reboot fixes it for a while. I try to keep my version of the SEEED firmware up to date also so it's not just older versions with the issue.

I just installed official openwrt with plain luci. Everything worked. Just had to set up DHCP interface for WAN under interfaces. 
Flashed this version with balenaEtcher. 
How to flash: https://wiki.seeedstudio.com/OpenWrt-Getting-Started/
Firmware: https://openwrt.org/toh/hwdata/raspberry_pi_foundation/raspberry_pi_foundation_raspberry_pi_cm4

Works good so far, will see in a couple of days how the throughput works.

**Comment by charliebearsson** [comment]
Been running for 24 hours now with official openWRT. Still the same throughput or even above. I pay for 500/500 mbit but now the throughput is 521/523 mbit. And 480/503 when using wireguard. Never going back to seeed firmware, not worth it!!

**Comment by LynnL4** [comment]
Close it and discuss it here.
https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/35
