### ISSUE TITLE
@charliebearsson  Hi, Still woring alright ? If so I will finally get round to reflashing the Seeed reRouter with OpenWRT this week !

### ISSUE THREAD

**Issue by charliebearsson** [Seeed-Studio/seeed-linux-openwrt#37]
@charliebearsson  Hi, Still woring alright ? If so I will finally get round to reflashing the Seeed reRouter with OpenWRT this week !

_Originally posted by @AaronNGray in https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/35#issuecomment-1368594050_
      

Still works great! Haven't rebooted it once for lack of speed. Very stable👌

**Comment by LynnL4** [comment]
Close it and discuss it here.
@AaronNGray in https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/35#issuecomment-1368594050
