### ISSUE TITLE
Is there a new release ?

### ISSUE THREAD

**Issue by AaronNGray** [Seeed-Studio/seeed-linux-openwrt#39]
Is there a new release and why is there no release tab in this GitHub repo ?

**Comment by LynnL4** [comment]
Hi,  A new release will be available within the next week. I have built it locally and now need to build a CI so that it can be built automatically.

**Comment by LynnL4** [comment]
![image](https://user-images.githubusercontent.com/51182126/222879709-97b90a49-1093-4e23-9e73-7fc4f3aee457.png)

**Comment by AaronNGray** [comment]
@LynnL4 is that TCP or UDP, and what happens with HTTP and HTTPS on port 80/443 ?

**Comment by LynnL4** [comment]
Okay, thanks, I'll check out this aspect in the new firmware.

**Comment by AaronNGray** [comment]
@LynnL4 Have you checked this out at all, Many thanks in advance.

**Comment by LynnL4** [comment]
> @LynnL4 Have you checked this out at all, Many thanks in advance.
It seems to be negotiating at 100mbps in some cases
https://github.com/Seeed-Studio/seeed-linux-openwrt/issues/42
