### ISSUE TITLE
will there be a 23.05 release? are there any compiles after May 2023? Where to find them?

### ISSUE THREAD

**Issue by perfessor101** [Seeed-Studio/seeed-linux-openwrt#43]
Hello, I bought the Dual Gigabit carrier board a few years ago, it's been working alright and I don't want to replace it for lack of security updates.

Would like to update and there are no new builds after 2023 May 17th from the looks of it ... so no 23.05 release?

is there a generic raspberry pi openwrt release that will continue to be maintained that I can switch to?

**Comment by AaronNGray** [comment]
https://openwrt.org/releases/23.05/notes-23.05.0

**Comment by Musicislife6984** [comment]
Any update on this yet? Looking forward to an updated version.

**Comment by LynnL4** [comment]
Hi， Since the CI is failing and no versions after 23.03 are being compiled, I will fix the CI

**Comment by LynnL4** [comment]
hi, 23.05 compiles fine, as you can see there is simple to compile with the following commands
 python3 . /scripts/build.py --config configs/bcm27xx_bcm2711_23_05_snaphsot_minimal

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
